// This file is generated by the FlutterFire CLI.
// To generate it, run: flutterfire configure
// Then import and use DefaultFirebaseOptions.currentPlatform in Firebase.initializeApp()

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1S05ZgPDFnAFA3OtWVGAsB2j3MsapHNg',
    appId: '1:696077530532:web:974f70980945061bd2fd31',
    messagingSenderId: '696077530532',
    projectId: 'weather-app-144ab',
    authDomain: 'weather-app-144ab.firebaseapp.com',
    storageBucket: 'weather-app-144ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1S05ZgPDFnAFA3OtWVGAsB2j3MsapHNg',
    appId: '1:696077530532:android:764dc950bb07e622d2fd31',
    messagingSenderId: '696077530532',
    projectId: 'weather-app-144ab',
    storageBucket: 'weather-app-144ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1S05ZgPDFnAFA3OtWVGAsB2j3MsapHNg',
    appId: '1:696077530532:ios:3380630c36641fbcd2fd31',
    messagingSenderId: '696077530532',
    projectId: 'weather-app-144ab',
    storageBucket: 'weather-app-144ab.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1S05ZgPDFnAFA3OtWVGAsB2j3MsapHNg',
    appId: '1:696077530532:ios:3380630c36641fbcd2fd31',
    messagingSenderId: '696077530532',
    projectId: 'weather-app-144ab',
    storageBucket: 'weather-app-144ab.firebasestorage.app',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1S05ZgPDFnAFA3OtWVGAsB2j3MsapHNg',
    appId: '1:696077530532:web:4ddad6fe2d95dc06d2fd31',
    messagingSenderId: '696077530532',
    projectId: 'weather-app-144ab',
    storageBucket: 'weather-app-144ab.firebasestorage.app',
  );
}
